version: "3.9"

services:
  mongodb:
    image: mongo:5.0.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    command: mongod --auth
    ports:
      - "${MONGO_PORT}:27017"

volumes:
  mongo_data:

