export enum ResponseId {
  ADD_GUESS_RESPONSE = 'ADD_GUESS_RESPONSE',
  COMMENCE_COUNTDOWN_RESPONSE = 'COMMENCE_COUNTDOWN_RESPONSE',
  START_ANIMATION_RESPONSE = 'START_ANIMATION_RESPONSE',
  STOP_ANIMATION_RESPONSE = 'STOP_ANIMATION_RESPONSE',
}
