name: Deploy testing
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_REMOTE_HOST }}
        username: ${{ secrets.SERVER_REMOTE_USER }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        script: |
          touch runner_was_her